# -*- coding: utf-8 -*-
"""Extra_Practical_10_bhavana_bambal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nE_8edRTlTuHfV2UP7mBC6pOtfMRztFZ
"""



"""Lab 10 Extra Practical: To perform Hierarchical Clustering using agglomerative methods and interpret dendrograms for cluster formation."""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import dendrogram, linkage

# 1. Load dataset
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/ML_DATASET/Spotify_Songs_Dataset.csv")

# 2. Select features
X = df[['danceability', 'energy']].dropna()

from sklearn.preprocessing import StandardScaler

# 3. Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import pandas as pd
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt

# 1. Load dataset
df = pd.read_csv("/content/drive/MyDrive/ML_DATASET/Spotify_Songs_Dataset.csv")

# 🔥 Reduce data size to avoid crash
df = df.sample(n=500, random_state=42)

# 2. Select features
X = df[['danceability', 'energy']].dropna()

# 3. Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

plt.figure(figsize=(8,5))
Z = linkage(X_scaled, method='ward')
dendrogram(Z)
plt.title('Dendrogram (Spotify Songs)')
plt.show()

from sklearn.cluster import AgglomerativeClustering
hc = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
clusters = hc.fit_predict(X_scaled)

df['Cluster'] = clusters
print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8,5))
sns.scatterplot(x='danceability', y='energy', hue='Cluster', data=df, palette='Set1')
plt.title('Spotify Songs Clustering')
plt.xlabel('Danceability')
plt.ylabel('Energy')
plt.show()