# -*- coding: utf-8 -*-
"""Extra_Practical_9_Bhavana_Bambal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSR5yzX9XThxWMzySlBo2-FblJkh7GHx
"""



"""Lab 9 Extra Practical: To implement the K-Means clustering algorithm and analyze the clustering results using appropriate evaluation techniques.

"""

#BHAVANA BAMBAL(CS23131)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

from google.colab import drive
drive.mount('/content/drive')

path ="/content/drive/MyDrive/ML_DATASET/WineQT.csv"
df=pd.read_csv(path)
df.head(5)

df.shape

df.columns

df.isnull().any().any()

X = df[['alcohol', 'quality']]

X.head()

X =df.iloc[:,[3,4]].values
print(X)

scaler = StandardScaler()
x_scaled = scaler.fit_transform(X)
print(x_scaled)

inertia_values = []
for k in range(1,11):
  kmeans = KMeans(n_clusters=k,random_state=42)
  kmeans.fit(x_scaled)
  inertia_values.append(kmeans.inertia_)
print(inertia_values)
plt.figure()
plt.plot(range(1,11),inertia_values,marker='o')
plt.xlabel("Number of Clusters(K)")
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal K')
plt.show()

kmeans = KMeans(n_clusters=8,random_state=42)
clusters = kmeans.fit_predict(x_scaled)
df['Cluster'] = clusters
print(df.head())

print("Inertia:",kmeans.inertia_)
sil_score = silhouette_score(x_scaled,clusters)
print("Silhouette Score:",sil_score)

plt.figure()
sns.scatterplot(x='residual sugar',
                y='chlorides',
                hue='Cluster',data=df,palette='Set1')
centroids = scaler.inverse_transform(kmeans.cluster_centers_)
plt.scatter(centroids[:,0],centroids[:,1],marker='X',s=200,c='black',label='Centroids')
plt.title("Wine Quality Segmentation using K-Means")
plt.legend()
plt.show()