# -*- coding: utf-8 -*-
"""ML_TAE_BHAVANA_BAMBAL_CS23131

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xpawGKtgK6X6tS7tZ1ujJ3xhYUBC1Hj
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install Required Libraries
!pip install pandas numpy matplotlib seaborn scikit-learn

# Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import Machine Learning Models
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

# Import Data Preprocessing and Evaluation Tools
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_squared_error

# Load Healthcare Cost Dataset from Google Drive
path = "/content/drive/MyDrive/ML_DATASET/insurance[1].csv"
df = pd.read_csv(path)
df.head()

# Display Dataset Information
df.info()
df.describe()

# Convert Categorical Features into Numerical Format
df = pd.get_dummies(df, drop_first=True)
df.head()

# Define Features (X) and Target Variable (y)
X = df.drop("charges", axis=1)
y = df["charges"]

# Split Dataset into Training and Testing Data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Apply Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define Machine Learning Models
models = {
"Linear Regression": LinearRegression(),
"Decision Tree": DecisionTreeRegressor(),
"Random Forest": RandomForestRegressor(),
"Support Vector Regression": SVR(),
"Gradient Boosting": GradientBoostingRegressor(),
"KNN": KNeighborsRegressor()
}

# Train Models and Calculate Performance Metrics
results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    results[name] = [r2, rmse]
results_df = pd.DataFrame(results, index=["R2 Score","RMSE"]).T
print(results_df)

# Visualize Model Performance Comparison
plt.figure(figsize=(10,5))
sns.barplot(x=results_df.index, y=results_df["R2 Score"])
plt.title("Model Comparison for Healthcare Cost Prediction")
plt.xticks(rotation=45)
plt.show()

# Visualize Age vs Healthcare Cost
plt.figure(figsize=(6,5))
sns.scatterplot(x=df["age"], y=df["charges"])
plt.title("Age vs Healthcare Cost")
plt.show()

# Visualize BMI vs Healthcare Cost
plt.figure(figsize=(6,5))
sns.scatterplot(x=df["bmi"], y=df["charges"])
plt.title("BMI vs Healthcare Cost")
plt.show()

# Visualize Smoking Status vs Healthcare Cost
sns.boxplot(x="smoker_yes", y="charges", data=df)
plt.title("Smoker vs Healthcare Cost")
plt.show()

# Feature Importance Analysis using Random Forest
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
importance = rf.feature_importances_
plt.figure(figsize=(8,5))
sns.barplot(x=importance, y=X.columns)
plt.title("Feature Importance for Healthcare Cost Prediction")
plt.show()

# Predict Healthcare Cost for a Sample Patient
sample = [[30, 28.5, 2, 0, 0, 1, 0, 0]]
sample_scaled = scaler.transform(sample)
prediction = rf.predict(sample_scaled)
print("Predicted Healthcare Cost:", prediction)

