# -*- coding: utf-8 -*-
"""PRACTICAL_8_ML_BHAVANA_BAMBAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16C4l9xC4dh_5rL66ssPTVBS5bHYVVxi-
"""



"""practical 8:

To apply Principal Component Analysis for dimensionality reduction
and visualize the transformed feature space.
"""

#BHAVANA BAMBAL(CS23131 )

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

iris = load_iris()
X = iris.data
y = iris.target



scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

print(X_pca)

print("Explained Variance Ratio: ",
      pca.explained_variance_ratio_)

plt.figure(figsize=(8, 6))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y)
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("PCA of Iris Dataset")
plt.colorbar()
plt.show()

pca = PCA()
pca.fit(X_scaled)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.show()