# -*- coding: utf-8 -*-
"""PRACTICAL_7_ML_BHAVANA_BAMBAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEpJvKCKPNwS0iaP3OTSbbqmhEVbsgvo

PRACTICAL NO 7
To apply Support Vector Machine for classification and analyze the
impact of different kernels on model accuracy.
"""

#bhavana bambaL(CS23131)

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from google.colab import drive
drive.mount('/content/drive')



path ="/content/drive/MyDrive/ML_DATASET/pulsar_stars.csv"
df=pd.read_csv(path)
df.head(5)

df.shape

df.columns

df.isnull().any().any()

X = df.drop(columns=['target_class'])
y = df['target_class']

X.head()

X = pd.get_dummies(X,dtype = int)

X.head()

x =df.iloc[:, :-1]
y =df.iloc[:, -1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=42)
X_train.shape,X_test.shape

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train

y_train

X_test

y_test

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc=SVC()
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print(f'Model accuracy score with default hyperparameters:\n{accuracy_score(y_test,y_pred):.4f}')

svc=SVC(C=100.0)

svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)

print('Model accuracy score with rbf kernel and C=100.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

linear_svc=SVC(kernel='linear',C=1.0)
linear_svc.fit(X_train,y_train)
y_pred=linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

linear_svc=SVC(kernel='linear',C=100.0)
linear_svc.fit(X_train,y_train)
y_pred=linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=100.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

linear_svc=SVC(kernel='linear',C=1000.0)
linear_svc.fit(X_train,y_train)
y_pred=linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1000.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

poly_svc=SVC(kernel='poly',C=1.0)
poly_svc.fit(X_train,y_train)
y_pred=poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

poly_svc=SVC(kernel='poly',C=100.0)
poly_svc.fit(X_train,y_train)
y_pred=poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=100.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

poly_svc=SVC(kernel='poly',C=1000.0)
poly_svc.fit(X_train,y_train)
y_pred=poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1000.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

sigmoid_svc=SVC(kernel='sigmoid',C=1.0)
sigmoid_svc.fit(X_train,y_train)
y_pred=sigmoid_svc.predict(X_test)
print('Model accuracy score with sigmoid kernel and C=1.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

sigmoid_svc=SVC(kernel='sigmoid',C=100.0)
sigmoid_svc.fit(X_train,y_train)
y_pred=sigmoid_svc.predict(X_test)
print('Model accuracy score with sigmoid kernel and C=100.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

sigmoid_svc=SVC(kernel='sigmoid',C=1000.0)
sigmoid_svc.fit(X_train,y_train)
y_pred=sigmoid_svc.predict(X_test)
print('Model accuracy score with sigmoid kernel and C=1000.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

from sklearn.metrics import confusion_matrix
print('Confusion Matrix')
cm=confusion_matrix(y_pred,y_test)
print(confusion_matrix(y_pred,y_test))