# -*- coding: utf-8 -*-
"""PRACTICAL_0_1_ML_BHAVANA_BAMBAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185erscWrP_BeZLcSTxVUrCW2FaahJxSG

Pre Lab: understanding google colab and python libraries for machine learning.[numpy,pandas,matplotlib,seaborn,scikit-learn]
"""

#BHAVANA BAMBAL(CS23131)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

a = np.array([1, 2, 3, 4])
b = np.zeros((2, 3))
c = np.ones((3, 3))
d = np.arange(0, 10, 2)
e = np.random.rand(3, 3)

print(a)
print(b)
print(c)
print(d)
print(e)

#ARRAY OPERATIONS
print(a.shape)
print(a.mean())
print(a.std())
print(np.sum(a))
print(np.max(a))

import pandas as pd
data = { 'Age': [25,30,35,40], 'Salary': [50000,60000,70000,80000], 'Department': ['IT','HR','IT','Finance'] }

df = pd.DataFrame(data)
print(df.shape)
print(df.head())
print(df)

print(df.info())
print(df.describe())

print(df['Salary'])
print(df[['Age','Department']])

df['Salary'].fillna(df['Salary'].mean(),inplace=True)

import pandas as pd
df_encoded = pd.get_dummies(df,drop_first=True)
print(df_encoded)

import matplotlib.pyplot as plt
x =[1,2,3,4]
y =[10,20,25,30]

plt.plot(x,y)
plt.xlabel('X values')
plt.ylabel('Y values')
plt.title('Line Plot')
plt.show()

plt.bar(x,y)
plt.title('Bar Plot')
plt.show()

plt.scatter(x,y)
plt.title('Scatter Plot')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

data = sns.load_dataset("iris")

sns.pairplot(data,hue='species')
plt.show()

corr = data.corr(numeric_only=True)
sns.heatmap(corr,annot=True)
plt.show()

sns.boxplot(x='species',y='sepal_length',data=data)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler