# -*- coding: utf-8 -*-
"""PRACTICAL_10_ML_BHAVANA_BAMBAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMkK7DakS2yxdsF_B1SlGjM9edSzHnej
"""



"""PRACTICAL NO 10
To perform Hierarchical Clustering using agglomerative methods
and interpret dendrograms for cluster formation.
"""

#BHAVANA BAMBAL(CS23131)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram,linkage

from google.colab import drive
drive.mount('/content/drive')

path ="/content/drive/MyDrive/ML_DATASET/Mall_Customers.csv"
df=pd.read_csv(path)
df.head(5)

X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
Z = linkage(X_scaled, method='ward')
dendrogram(Z)
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Euclidean Distance')
plt.show()

hc = AgglomerativeClustering(n_clusters=5, metric='euclidean', linkage='ward')
clusters = hc.fit_predict(X_scaled)



df['Cluster'] = clusters
print(df.head())

plt.figure(figsize=(8, 6))
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', hue='Cluster', data=df,

                palette='Set1')
plt.title('Hierarchical Clustering of Mall Customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.show()