# -*- coding: utf-8 -*-
"""PRACTICAL_3_ML_BHAVANA_BAMBAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-S6lLiZ3x3LZ85s6ff_GbmQvRUNaRAA

PRACTICAL NO : 3

Aim: To implement Logistic Regression for binary or multiclass classification problems and analyze the classification performance.
"""

#BHAVANA BAMBAL(CS23131)

import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset('iris')
df.head()

df.info()
df.shape
df.describe()

df['species'].unique()
df.isnull().sum()

df = df[df['species'] != 'setosa']
df.head()
df['species'].unique()
df.shape
df.info()

df['species'] = df['species'].map({'versicolor':0, 'virginica':1})
df.head()

X = df.iloc[:, :-1]
print(X)

Y = df.iloc[:, -1]
print(Y)

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, train_size=0.7, test_size=0.3, random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

from sklearn.model_selection import GridSearchCV

parameter = {
    'penalty':['l1','l2','elasticnet'],
    'C':[1,2,3,4,5,6,10,20,30,40,50],
    'max_iter':[100,200,300]
}

classifier_regressor = GridSearchCV(
    classifier, parameter, scoring='accuracy', cv=5
)

classifier_regressor.fit(X_train, Y_train)

print(classifier_regressor.best_params_)
print(classifier_regressor.best_score_)

y_pred = classifier_regressor.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
score = accuracy_score(Y_test, y_pred)
print(score)
print(classification_report(Y_test, y_pred))

import seaborn as sns
sns.pairplot(df, hue='species')