# -*- coding: utf-8 -*-
"""PRACTICAL_4_ML_BHAVANA_BAMBAL..

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yw_FF6zYgag2tRn-8QYW_OL9ktHhDFX
"""



"""#BHAVANA BAMBAL(CS23131)
# AIM to build and evaluate a decision tree model for classfication  tasks and study the effect of tree depth and splitting criteria
"""

import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

from google.colab import drive
drive.mount("/content/drive")

path="/content/drive/MyDrive/ML_DATASET/daily_weather.csv"
df=pd.read_csv(path)
df.head(5)

df.info()

df.shape

df.describe()

df.columns

df.isnull().any().any()

df.isnull().sum()

#print missing value
df[df.isnull().any(axis=1)]

df.drop('number', axis=1, inplace=True, errors='ignore')
df.columns

df.shape

before_rows=df.shape[0]
df = df.dropna()
after_rows = df.shape[0]
print("Before rows:",before_rows)
print("After rows:",after_rows)
print("The number of dropped rows are:",before_rows-after_rows)

df.shape

clean_data = df.copy()
clean_data ['high_humidity_label'] = (clean_data['relative_humidity_3pm']>24.99)*1
print(clean_data['high_humidity_label'])

clean_data.columns

clean_data.drop('relative_humidity_9am', axis=1, inplace=True, errors='ignore')
clean_data.drop('relative_humidity_3pm', axis=1, inplace=True, errors='ignore')
clean_data.columns

X=clean_data.iloc[:,:-1]
print(X)

Y=clean_data.iloc[:,-1]
print(Y)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

X_train

X_test

Y_train

Y_test

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler = scaler.transform(X_test)

humidity_classifier = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)
humidity_classifier.fit(X_train, Y_train)

import matplotlib.pyplot as plt
from sklearn import tree
plt.figure(figsize=(10,10))
tree.plot_tree(humidity_classifier, filled=True)

Y_pred = humidity_classifier.predict(X_test)
print(Y_pred)

#Accuraccy
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

print(confusion_matrix(Y_test, Y_pred))

print(classification_report(Y_test, Y_pred))