# -*- coding: utf-8 -*-
"""PRACTICAL_5_ML_BHAVANA_BAMBAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ypw8plcFnPd8wImCZ_1JRNxjh4N_u7bI

PRACTICAL NO 5
Aim:To implement the Random Forest algorithm and evaluate the model
performance using appropriate metrics.
"""

#BHAVANA BAMBAL(CS23131)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report

from google.colab import drive
drive.mount('/content/drive')

path="/content/drive/MyDrive/ML_DATASET/banking.csv"
df=pd.read_csv(path)
df.head(5)

df.shape

df.columns

df.isnull().any().any()

df[df.isnull().any(axis = 1)]

X = df.drop(columns=['y'])
y = df['y']

X.head()

X = pd.get_dummies(X,dtype = int)

X.head()

X.shape

X.columns

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=42)
X_train.shape,X_test.shape

from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100,n_jobs=-1,max_depth=5,oob_score=True,random_state=42)
rf_classifier.fit(X_train,y_train)

y_pred = rf_classifier.predict(X_test)
#print(y_pred)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print('Confusion Matrix')
cm=confusion_matrix(y_test,y_pred)
print(confusion_matrix(y_test,y_pred))

print('Accuracy Score')
print(accuracy_score(y_test,y_pred))

rf_classifier.oob_score_

print('Classification Report')
print(classification_report(y_test,y_pred))

rf=RandomForestClassifier(random_state=42,n_jobs=-1)
params={
    'max_depth':[2,3,5],
    'min_samples_leaf':[5,10,20],
    'n_estimators':[10,25,30,50]
}
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator=rf, param_grid=params, cv = 4, n_jobs=-1,verbose=1, scoring="accuracy")
grid_search.fit(X_train,y_train)

grid_search.best_score_

print(grid_search.best_params_)