# -*- coding: utf-8 -*-
"""PRACTICAL2_ML_BHAVANA_BAMBAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMDqfz9-EoT9WeuUFKQp5Nrak8_6ojQk
"""



"""Practical No. 2
Aim: To implement Linear Regression for predicting continuous target
variables and evaluate the model performance using appropriate metrics.
"""

print("BHAVANA BAMBAL(CS23131)")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score



#Step 1: Load Real Dataset
housing = fetch_california_housing()

#convert to dataframe
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['target'] = housing.target

print(df.head())

3.
df.shape
4.
df.describe()
5.
df.info()
6.
#step2: Feature & Target Split
x=df.drop('target',axis=1)
y=df['target']
7.
x.head()
8.
y.head()
9.
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

10.
x_train.shape

11

x_test.shape

12
y_train.shape
13

y_test.shape
14

#step 4: Train Linear Regression Model
model=LinearRegression()
model.fit(x_train,y_train)


15

#step 5: Prediction
y_pred=model.predict(x_test)
16

#step 6:Model Evaluation
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

17

print("\n Model Evaluation Matrices:")
print("Mean Absolute Error (mae):{mae}")
print("Mean Squared Error (mse):{mse}")
print("Root Mean Squared Error (rmse):{rmse}")
print("R squared Score(R2):{r2}")

18

plt.scatter(x_test['MedInc'], y_test, label='Actual Values')
plt.scatter(x_test['MedInc'], y_pred, label='Predicted Values')
plt.xlabel('MedInc')
plt.ylabel('House Value')
plt.title('Linear Regression on California Housing Dataset')
plt.legend()
plt.show()